In [1]:
import numpy as np

In [25]:
def print_state(state: np.ndarray):
    print(state[1:-1, 1:-1])

In [26]:
__state = np.zeros((9,9))
state = np.ones((7,7))
__state[1:8, 1:8] = 1
state = __state
print_state(state)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [27]:
player_position = (1,4)
enemy_position = (7,4)
state[player_position] = 2
state[enemy_position] = 3
print_state(state)

[[1. 1. 1. 2. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1. 1.]]


In [167]:
def possible_states(state: np.ndarray, current_player: int):
    possible_moves = find_possible_player_moves(state, current_player)
    for move_vector in possible_moves:
        partial_state = move_player(state, current_player, move_vector)
        possible_removals = find_possible_removals(partial_state)
        for remove_pos in possible_removals:
            yield remove_square(partial_state, remove_pos)

def find_possible_player_moves(state: np.ndarray, current_player: int) -> list:
        pos_x, pos_y = np.where(state == current_player)
        pos_x = pos_x[0]
        pos_y = pos_y[0]
        player_neighbourhood = state[pos_x - 1: pos_x + 2, pos_y - 1: pos_y + 2]
        x_positions = (np.where(player_neighbourhood == 1)[0] + pos_x - 1)
        y_positions = (np.where(player_neighbourhood == 1)[1] + pos_y - 1)
        return np.array((x_positions, y_positions)).T.tolist()

def find_possible_removals(state: np.ndarray) -> list:
    return np.array(np.where(state == 1)).T.tolist()
    
def move_player(state: np.ndarray, current_player: int, move_vector: tuple) -> np.ndarray:
    result = state.copy()
    result[move_vector[0], move_vector[1]] = current_player
    result[move_vector[0], move_vector[1]] = 1
    return result

def remove_square(state: np.ndarray, square_pos: tuple) -> np.ndarray:
    result = state.copy()
    result[square_pos[0], square_pos[1]] = 0
    return result

def simple_state_eval(state: np.ndarray, current_player: int) -> float:
    pass

In [170]:
list(possible_states(state, 2))

, 0., 0., 0., 0., 0., 0., 0.]]),
 array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 1., 2., 1., 1., 1., 0.],
        [0., 1., 1., 1., 1., 1., 1., 1., 0.],
        [0., 1., 1., 1., 1., 1., 1., 1., 0.],
        [0., 1., 1., 1., 1., 1., 1., 1., 0.],
        [0., 1., 1., 1., 1., 1., 1., 1., 0.],
        [0., 1., 1., 1., 1., 1., 1., 1., 0.],
        [0., 1., 1., 1., 3., 1., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 1., 2., 1., 1., 1., 0.],
        [0., 1., 1., 1., 1., 1., 1., 1., 0.],
        [0., 1., 1., 1., 1., 1., 1., 1., 0.],
        [0., 1., 1., 1., 1., 1., 1., 1., 0.],
        [0., 1., 1., 1., 1., 1., 1., 1., 0.],
        [0., 1., 1., 1., 1., 1., 1., 1., 0.],
        [0., 1., 1., 1., 3., 1., 1., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 1., 2., 1., 1., 1., 0.],
        [0., 1., 1., 1., 1., 1., 1., 1., 0.

In [135]:
np.where(player_neighbourhood)[1] + pos_y - 1

array([3, 4, 5, 3, 4, 5])

In [96]:
x_positions = (np.where(player_neighbourhood == 1)[0] + pos_x - 1)
y_positions = (np.where(player_neighbourhood == 1)[1] + pos_y - 1)
possible_moves = np.array((x_positions, y_positions)).T
np.array((x_positions, y_positions)).T.tolist()

[[1, 3], [1, 5], [2, 3], [2, 4], [2, 5]]

In [102]:
possible_removals = np.array(np.where(state == 1)).T.tolist()

In [108]:
for move_x, move_y in possible_moves:
    partial_state = state.copy()
    partial_state[move_x, move_y] = 2
    partial_state[pos_x, pos_y] = 1
    possible_removals = np.array(np.where(partial_state == 1)).T.tolist()
    try:
        possible_removals.remove([move_x, move_y])
    except ValueError:
        pass
    for remove_x, remove_y in possible_removals:
        possible_state = partial_state.copy()
        possible_state[remove_x, remove_y] == 0

In [81]:
state[[1, 1, 2, 2, 2], [3, 5, 3, 4, 5]]

array([1., 1., 1., 1., 1.])

In [80]:
state

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 2., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 3., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])