In [5]:
import numpy as np

In [90]:
class Player():

    def __init__(self, start_x, start_y):
        self.start_x = start_x
        self.start_y = start_y
        self.pos_x = start_x
        self.pos_y = start_y
    
    def return_position(self):
        return (pos_x, pos_y)

class Board():
    
    """Klasa implementująca plansze do gry."""
    
    
    """Pola planszy"""
    PLAYER = 2
    FREE_SQUARE = 1
    NO_SQUARE = 0

    
    
    def __init__(self, white_player, black_player, width=7, height=7):
        
        """
        Parameters
        ----------
        width : int, optional
            Szerokość planszy do gry (domyslnie 7)
        height : int, optional
            Wysokość planszy do gry (domyslnie 7)
        white_player : object
        
        black_player : object
        
        """
        
        self.width = width
        self.height = height
        #aktywny gracz (na posunieciu)
        self.active_player = white_player
        #nieaktywny gracz
        self.inactive_player = black_player
        #np array: zawiera informacje o stanie planszy
        self.board_status = np.ones((width,height))
        #tablica zawierajaca informacje o stanie planszy
        self.move_nuber = 0
        #lista legalnych posuniec aktywnego gracza
        self.legal_moves = []
        #lista legalnych usuniec pola aktywnego gracza
        self.legal_removes = []
            
            
    def init_players_pos(self):
        """Inicjalizacja poczatkowego ustawienia figur graczy"""
        self.board_status[self.active_player.start_x, self.active_player.start_y] = Board.PLAYER
        self.board_status[self.inactive_player.start_x, self.inactive_player.start_y] = Board.PLAYER

    def switch_turn(self):
        """Zmiana kolejki. Zamienia aktywnego gracza z nieaktywnym"""
        tmp_player = self.active_player
        self.active_player = self.inactive_player
        self.inactive_player = tmp_player
        
    def get_active_player_pos(self):        
        """Zwraca pozycję aktywnego gracza.

        Returns
        -------
        (int,int)
            Współrzedne gracza
        """
        return (self.active_player.pos_x, self.active_player.pos_y)
    
    def is_move_legal(self, move):
        """Sprawdza poprawność wprowadzonego ruchu.
        
        Parameters
        ----------
        move : (int, int)
            Współrzędne sprawdzanego ruchu.

        Returns
        -------
        bool
            Czy współrzędne znajdują się w zakresie planszy i czy wybrane pole jest równe 1
        """
        return (0 <= move[0] < self.height and 0 <= move[1] < self.width and
                self.board_status[move[0], move[1]] == Board.FREE_SQUARE)
    
    def set_legal_moves(self):
        """Wpisuje legalne ruchy do legal_moves."""
        player_pos = self.get_active_player_pos()
        self.legal_moves = []
         #góra
        if self.is_move_legal((player_pos[0],player_pos[1]+1)):
            self.legal_moves.append((player_pos[0],player_pos[1]+1))
        #dół
        if self.is_move_legal((player_pos[0],player_pos[1]-1)):
            self.legal_moves.append((player_pos[0],player_pos[1]-1))
        #prawo
        if self.is_move_legal((player_pos[0]+1,player_pos[1])):
            self.legal_moves.append((player_pos[0]+1,player_pos[1]))
        #lewo
        if self.is_move_legal((player_pos[0]-1,player_pos[1])):
            self.legal_moves.append((player_pos[0]-1,player_pos[1]))
        #lewe-górne
        if self.is_move_legal((player_pos[0]-1,player_pos[1]+1)):
            self.legal_moves.append((player_pos[0]-1,player_pos[1]+1))
        #prawe-górne
        if self.is_move_legal((player_pos[0]+1,player_pos[1]+1)):
            self.legal_moves.append((player_pos[0]+1,player_pos[1]+1))
        #lewe-dolne
        if self.is_move_legal((player_pos[0]-1,player_pos[1]-1)):
            self.legal_moves.append((player_pos[0]-1,player_pos[1]-1))
        #prawe-dolne
        if self.is_move_legal((player_pos[0]+1,player_pos[1]-1)):
            self.legal_moves.append((player_pos[0]+1,player_pos[1]-1))
    
    def set_legal_removes(self):
        """Wpisuje legalne usuniecia do legal_removes."""
        #Do przepisania petle
        self.legal_removes = []
        for x in range(self.width):
            for y in range(self.height):
                if (self.board_status[x,y] ==1):
                    self.legal_removes.append((x,y))
                 
    def make_move(self,move):
        """Wykonuje ruch na planszy. Update board_status, pozycji aktywnego gracza oraz ilosci wykonanych ruchów
        
        Parameters
        ----------
        move : (int, int)
            Współrzędne wykonywanego ruchu.
            
        Returns
        -------
        bool
            Czy udało sie wykonać ruch
        """
        current_position = self.get_active_player_pos()
        print (self.legal_moves)
        if (move in self.legal_moves):
            if self.move_nuber == 0:
                self.board_status[current_position[0]][current_position[1]] = Board.NO_SQUARE
                self.board_status[move[0], move[1]] = Board.PLAYER
                self.active_player.pos_x = move[0]
                self.active_player.pos_y = move[1]
            else:
                self.board_status[current_position[0], current_position[1]] = Board.FREE_SQUARE
                self.board_status[move[0], move[1]] = Board.PLAYER
                self.active_player.pos_x = move[0]
                self.active_player.pos_y = move[1]
            self.move_nuber = self.move_nuber + 1
        
        return (move in self.legal_moves)
    
    def remove_square(self,move):
        
        """Usuwa pole z planszy. Update board_status.
        
        Parameters
        ----------
        move : (int, int)
            Współrzędne usuwanego pola.
        """
        if (move in self.legal_moves):
            self.board_status[move[0], move[1]] = Board.NO_SQUARE
        
    def print_board(self):
        print (self.board_status)
        
        
    

In [82]:
white = Player(True, 6, 3)
black = Player(False, 0, 3)
board = Board(white, black)
board.init_players_pos()
board.print_board()

[[1. 1. 1. 2. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 2. 1. 1. 1.]]


In [83]:
board.set_legal_moves()

In [84]:
board.make_move((6,4))
board.print_board()
board.set_legal_moves()
board.legal_moves

[(6, 4), (6, 2), (5, 3), (5, 4), (5, 2)]
[[1. 1. 1. 2. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 2. 1. 1.]]


[(6, 5), (5, 4), (5, 5), (5, 3)]

In [85]:
board.make_move((5,4))
board.print_board()
board.set_legal_moves()
board.legal_moves

[(6, 5), (5, 4), (5, 5), (5, 3)]
[[1. 1. 1. 2. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 2. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1.]]


[(5, 5), (5, 3), (6, 4), (4, 4), (4, 5), (6, 5), (4, 3)]

In [86]:
board.make_move((4,4))
board.print_board()
board.set_legal_moves()
board.legal_moves

[(5, 5), (5, 3), (6, 4), (4, 4), (4, 5), (6, 5), (4, 3)]
[[1. 1. 1. 2. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 2. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1.]]


[(4, 5), (4, 3), (5, 4), (3, 4), (3, 5), (5, 5), (3, 3), (5, 3)]

In [87]:
board.make_move((5,6))
board.print_board()
board.set_legal_moves()
board.legal_moves

[(4, 5), (4, 3), (5, 4), (3, 4), (3, 5), (5, 5), (3, 3), (5, 3)]
[[1. 1. 1. 2. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 2. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1.]]


[(4, 5), (4, 3), (5, 4), (3, 4), (3, 5), (5, 5), (3, 3), (5, 3)]

In [88]:
board.set_legal_removes()
board.legal_removes

[(0, 0),
 (0, 1),
 (0, 2),
 (0, 4),
 (0, 5),
 (0, 6),
 (1, 0),
 (1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (2, 0),
 (2, 1),
 (2, 2),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (3, 0),
 (3, 1),
 (3, 2),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (4, 0),
 (4, 1),
 (4, 2),
 (4, 3),
 (4, 5),
 (4, 6),
 (5, 0),
 (5, 1),
 (5, 2),
 (5, 3),
 (5, 4),
 (5, 5),
 (5, 6),
 (6, 0),
 (6, 1),
 (6, 2),
 (6, 4),
 (6, 5),
 (6, 6)]